'use client'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// import 'react-custom-alert/dist/index.css'

import Wrapper from '@/components/Wrapper'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Work chat',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true} className={inter.className}>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  )
}
