name: Deploy to Production

on:
  push:
    branches:
      - cicd

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker Container
        run: sudo sh deploy_prod.sh
